version: '3'

services:
  dev:
   image: ubuntu:22.04
   container_name: dev
   network_mode: bridge
   ports:
     # Typical development ports
     - 3000-3012:3000-3012
     - 8080:8080
     - 3333:3333 # OpenOCD (gdbserver)
     - 4444:4444 # OpenOCD (telnet)
